"""add active_session_token to users

Revision ID: 597a077e1bbe
Revises: c1fb73985b76
Create Date: 2025-08-26 00:06:19.135298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597a077e1bbe'
down_revision = 'c1fb73985b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_session_token', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_active_session_token'), ['active_session_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_active_session_token'))
        batch_op.drop_column('active_session_token')

    # ### end Alembic commands ###
