"""add updated_at and indexes

Revision ID: 6147a1baa06c
Revises: 62c7358a3d7f
Create Date: 2025-08-08 15:38:19.568029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6147a1baa06c'
down_revision = '62c7358a3d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=24),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_tasks_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_done'))
        batch_op.drop_index(batch_op.f('ix_tasks_date_created'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
